# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

perm <- function(n, v) {
    .Call(`_taelor_perm`, n, v)
}

rcpp_hello_world <- function() {
    .Call(`_taelor_rcpp_hello_world`)
}

